// Campos preconfigurados
const fields = [
  { key: "nombreCliente", label: "Nombre cliente", type: "text" },
  { key: "fechaIngreso", label: "Fecha ingreso", type: "date" },
  { key: "kilometraje", label: "Kilometraje", type: "number" },
  { key: "presupuestoTotal", label: "Presupuesto total", type: "number" },
  { key: "rut", label: "RUT", type: "text" },
  { key: "telefono", label: "Teléfono", type: "text" },
  { key: "correo", label: "Correo", type: "text" },
  { key: "direccion", label: "Dirección", type: "text" },
  { key: "marca", label: "Marca", type: "text" },
  { key: "modelo", label: "Modelo", type: "text" },
  { key: "anio", label: "Año", type: "number" },
  { key: "patente", label: "Patente", type: "text" },
  { key: "vin", label: "N° chasis/VIN", type: "text" },
  { key: "color", label: "Color", type: "text" },
  { key: "combustible", label: "Combustible", type: "text" },
  { key: "transmision", label: "Transmisión", type: "text" },
  { key: "descripcionFalla", label: "Descripción falla", type: "text" },
  { key: "diagnostico", label: "Diagnóstico
